module ElephantInTheRoom
  module UkkonenSuffixTree
    class Edge
      @start: int

      @letters: Enumerable[String]

      attr_reader start: int

      attr_accessor from_node: Node

      def initialize: (int start, Enumerable[String] letters) -> void

      def to_s: () -> ::String

      def split: (int length) -> Node

      private

      def add_edge_to_split_node: (Node inner_node, int middle) -> Edge
    end

    class InnerEdge < Edge
      @to: int

      @to_node: Node

      attr_reader to: int

      attr_accessor to_node: Node

      def initialize: (int start, int to, Node to_node, Enumerable[String] letters) -> void

      def to_s: () -> ::String
    end
  end
end
