module ElephantInTheRoom
  module UkkonenSuffixTree
    class Node
      @letters: Enumerable[String]

      @name: String

      @edges: Hash[String, Edge]

      attr_reader name: String

      attr_reader edges: Hash[String, Edge]

      attr_accessor suffix_link: Node?

      def initialize: (Enumerable[String] letters) -> void

      def to_s: () -> ::String

      def add_edge: (int start) -> Edge

      def add_inner_edge: (int start, int to, Node to_node) -> Edge

      def set_all_edges: (Hash[String, Edge] edges) -> void
    end

    class EndNode < Node
      def initialize: (String name, Enumerable[String] letters) -> void
    end

    class InnerNode < Node
      attr_accessor from_edge: Edge

      def initialize: (String name, Enumerable[String] letters) -> void

      def replace_with_end_node: () -> void
    end
  end
end
