module ElephantInTheRoom
  module UkkonenSuffixTree
    module Printer
      def print_tree: () -> String

      private

      def print_node: () -> String

      def print_edge: (Edge edge) -> String
    end
  end
end
