# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in elephant_in_the_room-ukkonen_suffix_tree.gemspec
gemspec

gem "irb"
gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "rubocop", "~> 1.21"
gem "rubocop-rails-omakase", require: false, group: [ :development ]

gem "steep"
