module ElephantInTheRoom
  module UkkonenSuffixTree
    class ActivePoint
      @letters: Array[String]

      @node: Node

      @edge: Edge?

      @length: Integer

      @root: Node

      attr_accessor logger: ::Logger

      attr_accessor logger_redact_text: bool

      attr_reader node: Node

      attr_reader edge: Edge?

      attr_reader length: Integer

      def initialize: (Node root, Array[String] letters) -> void

      def to_s: () -> ::String

      def split_active_edge: () -> InnerNode

      def move_after_suffix_inserted: () -> void

      def advance_active_point: (String letter) -> (bool)
    end
  end
end
