module ElephantInTheRoom
  module UkkonenSuffixTree
    class Node
      include Printer

      attr_accessor logger: Logger?
      attr_accessor logger_redact_text: bool

      @letters: Array[String]
      @name: String
      @edges: Hash[String, Edge]

      attr_reader name: String
      attr_reader edges: Hash[String, Edge]
      attr_writer edges: Hash[String, Edge]
      attr_accessor suffix_link: Node?

      def initialize: (Array[String] letters) -> void

      def to_s: () -> String

      def add_edge: (Integer start) -> Edge

      def add_inner_edge: (Integer start, Integer to, Node to_node) -> InnerEdge

      def set_all_edges: (Hash[String, Edge] edges) -> void
    end

    class EndNode < Node
      def initialize: (String name, Array[String] letters) -> void
    end

    class InnerNode < Node
      attr_accessor from_edge: InnerEdge

      def initialize: (String name, Array[String] letters) -> void

      def replace_with_end_node: () -> void
    end
  end
end
